### PR TITLE
Feature/custom request

### PR DESCRIPTION
**Pull request by gritsenko-konstantin**
Hey!

We need to send custom request to sync nodes and clean some stuff on all the nodes.

### CODE REVIEW

**Comment by darrachequesne** [comment]
Thanks for the pull request! I'm wondering whether we should add the other request types too, what do you think? And maybe extract that part from `socket.io-redis` in its own package?

**Comment by gritsenko-konstantin** [comment]
hey!

thank you for so fast response :) appreciate this!

yes! extracting common types to sub package sound like a great idea!

**Comment by gritsenko-konstantin** [comment]
Oh!
and i forget to update README file with updates.

will update that

**Comment by gritsenko-konstantin** [comment]
how we can extract that?
any suggestions?

**Comment by gritsenko-konstantin** [comment]
@darrachequesne

**Comment by jackycute** [comment]
Thank you @gritsenko-konstantin!

This PR is also pretty useful for me.
In my case, I need to send events to all nodes to make some process before sending to all clients, so it's more like a relay mechanism.

**Comment by JohnXLivingston** [comment]
I'd like this PR to be merged. Any news?

**Comment by darrachequesne** [comment]
For future readers: this was Implemented as `serverSideEmit()` in https://github.com/socketio/socket.io-redis-emitter/commit/5feabdac98f0ae44f30dcf36a29a8be328be139e.

Reference: https://socket.io/docs/v4/adapter/#emitter

**Pull request closed without merging**
